### ISSUE TITLE
Am implementing juspay plugin but not having SHA Key please provide me SHA Key am getting this error

### ISSUE THREAD

**Issue by urusamadni123** [deep-rooted-co/juspay_flutter#12]
Git error. Command: `git clone --mirror git@github.com:deep-rooted-co/juspay_flutter.git C:\flutter\.pub-cache\git\cache\juspay_flutter-025068dbc1c42ddc50e6437bfee51d8135f15222`
stdout: 
stderr: Cloning into bare repository 'C:\flutter\.pub-cache\git\cache\juspay_flutter-025068dbc1c42ddc50e6437bfee51d8135f15222'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by sachinsudheendra** [comment]
Please use the https URL in your `pubspec.yaml`. We've updated the README.md as well.

For example,
```
dependencies:
  juspay_flutter:
    git:
      url: https://github.com/deep-rooted-co/juspay_flutter.git
      ref: 4ebb4b062a130d6612aad9c627bbc611d9b4c82f
```
